name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux-amd64:
    name: Build linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Building
        run: make build-linux-amd64
      - name: Artifacts listing
        run: make status
      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: h2tp-linux-amd64
          path: target/*

  build-linux-arm64:
    name: Build linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Building
        run: make build-linux-arm64
      - name: Artifacts listing
        run: make status
      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: h2tp-linux-arm64
          path: target/*

  build-linux-arm:
    name: Build linux/arm
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Building
        run: make build-linux-arm
      - name: Artifacts listing
        run: make status
      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: h2tp-linux-arm
          path: target/*

  build-windows-amd64:
    name: Build windows/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Building
        run: make build-windows-amd64
      - name: Artifacts listing
        run: make status
      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: h2tp-windows-amd64
          path: target/*

  build-macos-amd64:
    name: Build macos/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Building
        run: make build-macos-amd64
      - name: Artifacts listing
        run: make status
      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: h2tp-macos-amd64
          path: target/*