name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Building
        run: make build

      - name: Artifacts listing
        run: make status

      - uses: actions/upload-artifact@2
        name: macos/amd64 artifact
        with:
          name: h2tp
          path: target/darwin/amd64/h2tp

      - uses: actions/upload-artifact@2
        name: linux/amd64 artifact
        with:
          name: h2tp
          path: target/linux/amd64/h2tp

      - uses: actions/upload-artifact@2
        name: linux/arm64 artifact
        with:
          name: h2tp
          path: target/linux/arm64/h2tp

      - uses: actions/upload-artifact@2
        name: linux/arm artifact
        with:
          name: h2tp
          path: target/linux/arm/h2tp

      - uses: actions/upload-artifact@2
        name: windows/amd64 artifact
        with:
          name: h2tp
          path: target/windows/amd64/h2tp.exe