name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o target/h2tp-darwin-amd64 main.go

      - name: Build Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o target/h2tp-windows-amd64 main.go

      - name: Build Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o target/h2tp-linux-amd64 main.go

      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: h2tp
          path: target/*
